
delete from task;

insert into task
    (uid, creation_date, modification_date)
values
    ('TASK_UID_01', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('TASK_UID_02', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('TASK_UID_03', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('TASK_UID_04', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

delete from execution_time;

insert into execution_time
    ("value", task_id, creation_date, modification_date)
values
    (100L, "TASK_UID_01", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (200L, "TASK_UID_01", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (400L, "TASK_UID_01", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (100L, "TASK_UID_02", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (150L, "TASK_UID_02", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (200L, "TASK_UID_02", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (200L, "TASK_UID_03", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (400L, "TASK_UID_03", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (500L, "TASK_UID_03", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (200L, "TASK_UID_04", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (300L, "TASK_UID_04", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (400L, "TASK_UID_04", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
